import Head from "next/head";
import Cart from "../components/cart/cart";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";

function CartPage() {
    return (
        <>
            <Head>
                <title>Cart Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Cart />
            <Footer />
        </>
    );
}

export default CartPage;