import Head from 'next/head'
import Banner from '../components/banner/banner'
import Footer from '../components/footer/footer'
import Header from '../components/header/header'
import HotProduct from '../components/hot-product/hot-product'
import ShopPolicy from '../components/policy/policy'

export default function Home() {
  return (
    <>
      <Head>
        <title>Eira Been</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <HotProduct />
      <ShopPolicy />
      <Footer />
    </>
  )
}
