import Head from "next/head";
import { useRouter } from "next/router";
import { FunctionComponent, useEffect, useState } from "react";
import Detail from "../../components/detail/detail";
import Footer from "../../components/footer/footer";
import Header from "../../components/header/header";
import Loading from "../../components/loading/loading";
import { Product } from "../../types/product";
import { useQuery } from '@apollo/client'
import { GetProductByShortLinkVars, GetProductByShortLinkData, GET_PRODUCT_BY_SHORT_LINK } from "../../graphql/queries/product";

interface ProductDetailProps {

}

const ProductDetail: FunctionComponent<ProductDetailProps> = () => {
    const [product, setProduct] = useState<Product | null>()

    const { query } = useRouter()
    const { data, error } = useQuery<GetProductByShortLinkData, GetProductByShortLinkVars>(GET_PRODUCT_BY_SHORT_LINK, {
        variables: {
            short_link: String(query?.short_link)
        }
    })

    useEffect(() => {
        if(data && !error) {
            setProduct(data.product)
        }
    }, [data, error])

    if (!product) {
        return (
            <>
                <Head>
                    <title>Product</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Loading />
            </>
        )
    }

    return (
        <>
            <Head>
                <title>Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Detail product={product}/>
            <Footer />
        </>
    );
}

export default ProductDetail;